# Generated by Django 4.2.3 on 2024-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'ポケモン',
                'verbose_name_plural': 'ポケモン',
                'db_table': 'pokemon',
            },
        ),
    ]
